---
- hosts: webserver
  remote_user: ansible
  become: yes
  become_method: sudo
  vars:
    packages:
    - php
    - httpd
    - mariadb
    - mariadb-server  

  tasks:
  - name: Epel repo is installed
    yum: 
      name: epel-release
      state: present

  - name: Install packages
    yum:
      name: "{{ packages }}"
      state: latest

  - name: Configure virtual host
    template:
      src: ./vhost_template.j2
      dest: /etc/httpd/conf.d/vhost.conf
      owner: root
      group: root
      mode: 0644
    notify: Restart webserver
 
  - name: Web server running and enabled
    service:
      name: httpd
      state: started
      enabled: true

  - name: Verify is apache running
    command: systemctl status httpd
    register: httpd_status

  - name: Show HTTPD STATUS
    debug: 
      var: httpd_status
 
  - name: Copy content of site
    copy:
      src: ./index.html
      dest: /var/www/html
      owner: root
      group: root
      mode: 0664
    notify: Restart webserver

  - name: Apache running and enabled
    service:
      name: httpd
      state: started
      enabled: true

  - name: mariadb running and enabled
    service:
      name: mariadb
      state: started
      enabled: true

  - name: Varify is mariadb running
    command: systemctl status mariadb    
    register: mariadb_status

  - name: Show MARIADB STATUS
    debug:
      var: mariadb_status      

  - name: Open firewall httpd port (http)
    firewalld:
      service: http
      permanent: yes
      state: enabled
      zone: public     

  - name: Open firewall httpd port (https)     
    firewalld:
      service: https
      permanent: yes
      state: enabled
      zone: public

  handlers:
  - name: Restart webserver
    service: 
      name: httpd
      state: restarted
      enabled: yes

                      

